// .cpp autogenerated by cmake

#define BUILD_DETERMINISTIC 0

const char * auto_config_build[]
{
    "VERSION_FULL", "ClickHouse 19.3.4",
    "VERSION_DESCRIBE", "v19.3.4-testing",
    "VERSION_INTEGER", "19003004",

#if BUILD_DETERMINISTIC
    "SYSTEM", "Linux",
#else
    "VERSION_GITHASH", "263e69e861b769eae7e2bcc79d87673e3a08d376",
    "VERSION_REVISION", "54415",
    "BUILD_DATE", "2019-03-16",
    "SYSTEM", "Linux-4.18.0-16-generic",
#endif

    "BUILD_TYPE", "Debug",
    "SYSTEM_PROCESSOR", "x86_64",
    "LIBRARY_ARCHITECTURE", "x86_64-linux-gnu",
    "CMAKE_VERSION", "3.12.1",
    "C_COMPILER", "/usr/bin/cc",
    "C_COMPILER_VERSION", "8.2.0",
    "CXX_COMPILER", "/usr/bin/c++",
    "CXX_COMPILER_VERSION", "8.2.0",
    "C_FLAGS", " -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer  -Wall  -no-pie -g -O0 -g3 -ggdb3 -fno-inline ",
    "CXX_FLAGS", " -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -no-pie -g -O0 -g3 -ggdb3 -fno-inline ",
    "LINK_FLAGS", " -fuse-ld=gold -static-libgcc -static-libstdc++",
    "BUILD_COMPILE_DEFINITIONS", "",
    "BUILD_INCLUDE_DIRECTORIES", "",
    "STATIC", "ON",
    "USE_EMBEDDED_COMPILER", "0",
    "USE_INTERNAL_MEMCPY", "ON",
    "USE_GLIBC_COMPATIBILITY", "ON",
    "USE_JEMALLOC", "1",
    "USE_TCMALLOC", "",
    "USE_UNWIND", "1",
    "USE_ICU", "1",
    "USE_MYSQL", "1",
    "USE_RE2_ST", "1",
    "USE_VECTORCLASS", "",
    "USE_RDKAFKA", "1",
    "USE_CAPNP", "1",
    "USE_POCO_SQLODBC", "",
    "USE_POCO_DATAODBC", "1",
    "USE_POCO_MONGODB", "1",
    "USE_POCO_NETSSL", "1",
    "USE_BASE64", "1",
    "USE_PROTOBUF", "1",
    "USE_BROTLI", "1",

    nullptr, nullptr
};
